### PR TITLE
Use node_encrypt and don't save key to disk

### PR DESCRIPTION
**Pull request by ross-w**
Remove potentially failing cruft with scrubbing and ramdisks etc.

### CODE REVIEW

**Comment by ross-w** [comment]
@sammcj Have a look over this when you get a moment

**Comment by sammcj** [comment]
Github is so terrible to use, I wish I put this on GitLab instead, I've added a comment that you can't see:

screen shot 2017-06-28 at 10 14 41 am

**Comment by sammcj** [comment]
Github is so terrible to use, I wish I put this on GitLab instead, I've added a comment that you can't see:

screen shot 2017-06-28 at 10 14 41 am

**Comment by sammcj** [comment]
garhhh I hate GitHub

**Comment by ross-w** [comment]
Updated

**Pull request merged**
